### ISSUE TITLE
Weird issue with font...

### ISSUE THREAD

**Issue by csolorio** [lczx/watcher#1]
When I download the whole project as a zip, the otf file gets corrupted somehow and I have to download it separately. I know it's not an issue of the project itself, but of github... Anyway, just to let you know.

**Comment by lczx** [comment]
Thanks very much for your report and yes, I have already noticed this behavior.
This could be "fixed" on my side by recommitting the file without using Git LFS but as you said the problem has to do with GitHub itself (git-lfs/git-lfs#903).
